[package]
name = "tokenizers-scala"
version = "0.1.0"
authors = ["Sören Brunk <soeren@brunk.io>"]
edition = "2021"

[dependencies]
tokenizers = "0.13.3"
jni = "0.21.1"

[lib]
crate_type = ["cdylib"]

[build-dependencies]
cbindgen = "0.24.0"